#正式环境
server:
  port: 8080
  servlet:
    context-path: /springboot2


#数据库连接池
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: zqf0529630
    #性能调优
    #hikari.....

#项目常量
user-entity:
  name: 猪猪
  age: 2
